### ISSUE TITLE
what is the meta-graph type list(e.g.NG20TypeList) mean?

### ISSUE THREAD

**Issue by yiranxijie** [DeiPlusAY/semihin#3]
hello, I have no idea about the NG20TypeList,some of which like this: `NG20TypeList = [['organization'],['business'],['astronomy','spaceflight'], ['computer'],['sports','automotive'],['medicine','organization','biology','business'],['computer','astronomy','spaceflight','automotive'], [''], ['location']],` I don't know how it is generated?or even the empty list means what?

**Comment by DeiPlusAY** [comment]
This are the types of entities to be included in each meta-graph, and is generated (pretty randomly) manually. The empty string one [''] means that all entities are included, which is a full graph.
